### ISSUE TITLE
TrackedArray

### ISSUE THREAD

**Issue by mwpastore** [pzuraq/tracked-built-ins#11]
Does it make sense to introduce a TrackedArray here: more than an Array, less than an EmberArray?

**Comment by pzuraq** [comment]
Yes, we had one previously but I removed it because it was trying to do too much in order to be backwards compatible with IE11.

Now, I think IE11 is just something we can't support for arrays unfortunately. So I want to add a new version with support for modern browsers, and if we can completely remove it if the user does still support IE. I'm not sure that's possible (or easy) though, so it may just need to be something they have to be aware of before using it.

**Comment by pzuraq** [comment]
It may also need to be a separate package for the time being.

**Comment by pzuraq** [comment]
This has been added in v1.0.0! 😄

**Comment by mwpastore** [comment]
Amazing! Break a leg tomorrow!
